import type { Answers } from '../src/lib/forms/types';
import type { FormSupplementAnswers } from '../src/types/wizard';

export function createBaseAnswers(): Answers {
  return {
    petitioner_is_citizen: 'yes',
    currently_married: 'yes',
    beneficiary_in_us: 'yes',
    entered_legally: 'yes',
    g1145_contact_preference: 'Petitioner',
    include_i765: 'yes',
    include_i131: 'yes',
    payment_method: 'Credit card (Form G-1450)',
    i693_submission_timing: 'Include sealed I-693 with the initial filing',

    petitioner_first_name: 'Alex',
    petitioner_middle_name: 'Marie',
    petitioner_last_name: 'Sponsor',
    petitioner_has_aliases: 'no',
    petitioner_dob: '1990-01-02',
    petitioner_sex: 'Female',
    petitioner_city_birth: 'Chicago',
    petitioner_country_birth: 'United States',
    petitioner_citizenship_how: 'Birth in the United States',
    petitioner_ssn: '111-22-3333',
    petitioner_has_anumber: 'no',
    petitioner_has_uscis_account: 'no',
    petitioner_phone: '3125551111',
    petitioner_email: 'petitioner@example.com',
    petitioner_mailing_address: {
      street: '123 Main St',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      country: 'United States',
    },
    petitioner_physical_same_as_mailing: 'yes',

    beneficiary_first_name: 'Jordan',
    beneficiary_middle_name: 'Lee',
    beneficiary_last_name: 'Applicant',
    beneficiary_has_aliases: 'no',
    beneficiary_dob: '1992-03-04',
    beneficiary_sex: 'Male',
    beneficiary_city_birth: 'Toronto',
    beneficiary_country_birth: 'Canada',
    beneficiary_country_citizenship: 'Canada',
    beneficiary_ssn_status: 'Has SSN',
    beneficiary_ssn: '222-33-4444',
    beneficiary_has_anumber: 'yes',
    beneficiary_anumber: 'A123456789',
    beneficiary_has_uscis_account: 'no',
    beneficiary_passport_number: 'P12345678',
    beneficiary_passport_country: 'Canada',
    beneficiary_passport_expiry: '2030-01-01',
    beneficiary_phone: '7735552222',
    beneficiary_email: 'beneficiary@example.com',
    beneficiary_mailing_address: {
      street: '123 Main St',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      country: 'United States',
    },
    beneficiary_physical_same_as_mailing: 'yes',

    marriage_date: '2024-06-01',
    marriage_city: 'Chicago',
    marriage_state: 'IL',
    marriage_country: 'United States',
    petitioner_prior_marriages: 'no',
    beneficiary_prior_marriages: 'no',
    has_children: 'no',
    beneficiary_parents_list: [
      {
        relationship: 'Mother',
        given_name: 'Pat',
        family_name: 'Applicant',
        country_birth: 'Canada',
      },
      {
        relationship: 'Father',
        given_name: 'Sam',
        family_name: 'Applicant',
        country_birth: 'Canada',
      },
    ],

    beneficiary_address_history: [
      {
        street: '123 Main St',
        city: 'Chicago',
        state: 'IL',
        zip: '60601',
        country: 'United States',
        from_date: '2022-01-01',
        present: 'yes',
      },
    ],

    beneficiary_employment_history: [
      {
        employer_name: 'Acme Corp',
        occupation: 'Designer',
        city: 'Chicago',
        country: 'United States',
        from_date: '2022-01-01',
        present: 'yes',
      },
    ],
    petitioner_employment_status: 'Employed',
    petitioner_employer: 'Open Work Co',
    petitioner_job_title: 'Engineer',
    petitioner_employment_start_date: '2020-02-01',
    petitioner_employer_address: {
      street: '500 Market St',
      city: 'Chicago',
      state: 'IL',
      zip: '60602',
      country: 'United States',
    },
    petitioner_annual_income: '85000',
    sponsor_household_size: '2',
    sponsor_recent_tax_year: '2025',
    sponsor_total_income: '84000',
    sponsor_tax_filed: 'yes',
    sponsor_has_assets: 'no',
    needs_joint_sponsor: 'no',

    current_visa_type: 'B-1/B-2 (Visitor / Tourist)',
    i94_number: '12345678901',
    last_entry_date: '2024-01-15',
    last_entry_port: 'ORD Airport',
    status_d_s: 'no',
    authorized_until: '2024-07-15',
    overstayed: 'no',
    unauthorized_employment: 'no',
    prior_uscis_filings: 'no',
    deported_or_removed: 'no',
    removal_proceedings: 'no',

    travel_outside_us: 'yes',
    travel_history: [
      {
        destination: 'Canada',
        departure_date: '2023-12-20',
        return_date: '2024-01-03',
      },
    ],
    i765_has_prior_ead: 'no',
    i131_trip_purpose: 'Visit family and return to the United States',
    i131_countries_to_visit: 'Canada',
    i131_trip_length_days: '14',
    i131_has_prior_travel_document: 'no',

    criminal_arrests: 'no',
    drug_use: 'no',
    health_conditions: 'no',
    immigration_fraud: 'no',
    polygamy: 'no',
    terrorist_activity: 'no',
    public_charge_concern: 'no',

    has_marriage_certificate: 'yes',
    has_birth_certificates: 'yes',
    has_passport_photos: 'yes',
    has_beneficiary_passport: 'yes',
    has_i94: 'yes',
    has_petitioner_citizenship_evidence: 'yes',
    has_tax_returns: 'yes',
    has_joint_evidence: 'yes',
    i693_exam_completed: 'yes',
    i693_exam_date: '2026-02-01',
    i693_envelope_ready: 'yes',
    beneficiary_vaccination_records_available: 'yes',
  };
}

export function createPaymentSupplements(): FormSupplementAnswers {
  return {
    payment_cardholder_given_name: 'Alex',
    payment_cardholder_middle_name: 'Marie',
    payment_cardholder_family_name: 'Sponsor',
    payment_billing_street: '123 Main St',
    payment_billing_city: 'Chicago',
    payment_billing_state: 'IL',
    payment_billing_zip: '60601',
    payment_daytime_phone: '3125551111',
    payment_email: 'petitioner@example.com',
    payment_card_type: 'Visa',
    payment_card_number: '4111111111111111',
    payment_expiration_date: '12/2030',
    payment_cvv: '123',
    payment_authorized_amount: '3005',
  };
}
